services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_DATABASE='desigNwear'
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  
  server:
    build: .
    depends_on:
      - mysqldb
    restart: unless-stopped
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    env_file: ./.env
    environment:
      - JWT_SECRET=$JWT_SECRET
      - JWT_LIFETIME=$JWT_LIFETIME

volumes:
  db:

  
  